/* Generated by the Nim Compiler v1.9.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217746 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555824 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI33555824 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555824.node = NNI33555824;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;
var NNI134217746 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217746.node = NNI134217746;
var NNI33555177 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555177.node = NNI33555177;
NTI33555177.base = NTI33555175;
NTI134217746.base = NTI33555177;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555176;

function mnewString(len_33556950) {
        return new Array(len_33556950);
  

  
}

function arrayConstr(len_33557252, value_33557253, typ_33557254) {
        var result = new Array(len_33557252);
    for (var i = 0; i < len_33557252; ++i) result[i] = nimCopy(null, value_33557253, typ_33557254);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557209, src_33557210, ti_33557211) {
  var result_33557220 = null;

    switch (ti_33557211.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557200(ti_33557211))) {
      result_33557220 = src_33557210;
      }
      else {
        result_33557220 = [src_33557210[0], src_33557210[1]];
      }
      
      break;
    case 19:
            if (dest_33557209 === null || dest_33557209 === undefined) {
        dest_33557209 = {};
      }
      else {
        for (var key in dest_33557209) { delete dest_33557209[key]; }
      }
      for (var key in src_33557210) { dest_33557209[key] = src_33557210[key]; }
      result_33557220 = dest_33557209;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557211.base == null))) {
      result_33557220 = nimCopy(dest_33557209, src_33557210, ti_33557211.base);
      }
      else {
      if ((ti_33557211.kind == 17)) {
      result_33557220 = (dest_33557209 === null || dest_33557209 === undefined) ? {m_type: ti_33557211} : dest_33557209;
      }
      else {
        result_33557220 = (dest_33557209 === null || dest_33557209 === undefined) ? {} : dest_33557209;
      }
      }
      nimCopyAux(result_33557220, src_33557210, ti_33557211.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557210)) { 
        if(dest_33557209 === null || dest_33557209 === undefined || dest_33557209.length != src_33557210.length) {
          dest_33557209 = new src_33557210.constructor(src_33557210);
        } else {
          dest_33557209.set(src_33557210, 0);
        }
        result_33557220 = dest_33557209;
      } else {
        if (src_33557210 === null) {
          result_33557220 = null;
        }
        else {
          if (dest_33557209 === null || dest_33557209 === undefined || dest_33557209.length != src_33557210.length) {
            dest_33557209 = new Array(src_33557210.length);
          }
          result_33557220 = dest_33557209;
          for (var i = 0; i < src_33557210.length; ++i) {
            result_33557220[i] = nimCopy(result_33557220[i], src_33557210[i], ti_33557211.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557210 === null) {
        result_33557220 = null;
      }
      else {
        if (dest_33557209 === null || dest_33557209 === undefined || dest_33557209.length != src_33557210.length) {
          dest_33557209 = new Array(src_33557210.length);
        }
        result_33557220 = dest_33557209;
        for (var i = 0; i < src_33557210.length; ++i) {
          result_33557220[i] = nimCopy(result_33557220[i], src_33557210[i], ti_33557211.base);
        }
      }
    
      break;
    case 28:
            if (src_33557210 !== null) {
        result_33557220 = src_33557210.slice(0);
      }
    
      break;
    default: 
      result_33557220 = src_33557210;
      break;
    }

  return result_33557220;

}

function cstrToNimstr(c_33556851) {
      var ln = c_33556851.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556851.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556851.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556854) {
  var result_33556855 = null;

    var res_33556893 = newSeq_33556872((s_33556854).length);
    var i_33556894 = 0;
    var j_33556895 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556894 < (s_33556854).length)) break Label2;
          var c_33556896 = s_33556854[i_33556894];
          if ((c_33556896 < 128)) {
          res_33556893[j_33556895] = String.fromCharCode(c_33556896);
          i_33556894 += 1;
          }
          else {
            var helper_33556909 = newSeq_33556872(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556910 = c_33556896.toString(16);
                  if ((((code_33556910) == null ? 0 : (code_33556910).length) == 1)) {
                  helper_33556909.push("%0");;
                  }
                  else {
                  helper_33556909.push("%");;
                  }
                  
                  helper_33556909.push(code_33556910);;
                  i_33556894 += 1;
                  if ((((s_33556854).length <= i_33556894) || (s_33556854[i_33556894] < 128))) {
                  break Label3;
                  }
                  
                  c_33556896 = s_33556854[i_33556894];
                }
            };
++excHandler;
            try {
            res_33556893[j_33556895] = decodeURIComponent(helper_33556909.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556893[j_33556895] = helper_33556909.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556895 += 1;
        }
    };
    if (res_33556893.length < j_33556895) { for (var i = res_33556893.length ; i < j_33556895 ; ++i) res_33556893.push(null); }
               else { res_33556893.length = j_33556895; };
    result_33556855 = res_33556893.join("");

  return result_33556855;

}

function raiseException(e_33556642, ename_33556643) {
    e_33556642.name = ename_33556643;
    if ((excHandler == 0)) {
    unhandledException(e_33556642);
    }
    
    e_33556642.trace = nimCopy(null, rawWriteStackTrace_33556599(), NTI33554449);
    throw e_33556642;

  
}

function addInt(a_33556997, b_33556998) {
        var result = a_33556997 + b_33556998;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557262, a_33557263, b_33557264) {
  var result_33557265 = 0;

  BeforeRet: {
    if (((a_33557263 <= i_33557262) && (i_33557262 <= b_33557264))) {
    result_33557265 = i_33557262;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557265;

}

function chckIndx(i_33557257, a_33557258, b_33557259) {
  var result_33557260 = 0;

  BeforeRet: {
    if (((a_33557258 <= i_33557257) && (i_33557257 <= b_33557259))) {
    result_33557260 = i_33557257;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557257, a_33557258, b_33557259);
    }
    
  };

  return result_33557260;

}

function mulInt(a_33557005, b_33557006) {
        var result = a_33557005 * b_33557006;
    checkOverflowInt(result);
    return result;
  

  
}

function makeNimstrLit(c_33556848) {
      var result = [];
  for (var i = 0; i < c_33556848.length; ++i) {
    result[i] = c_33556848.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33557001, b_33557002) {
        var result = a_33557001 - b_33557002;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 218;
var objectID_738197675 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function catch_973078579(future_973078581, onReject_973078582) {
  var result_973078583 = null;

  var F = {procname: "catch.catch", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
    F.line = 267;
    result_973078583 = future_973078581.catch(onReject_973078582)
  framePtr = F.prev;

  return result_973078583;

}

function add_33556386(x_33556387, x_33556387_Idx, y_33556388) {
          if (x_33556387[x_33556387_Idx] === null) { x_33556387[x_33556387_Idx] = []; }
      var off = x_33556387[x_33556387_Idx].length;
      x_33556387[x_33556387_Idx].length += y_33556388.length;
      for (var i = 0; i < y_33556388.length; ++i) {
        x_33556387[x_33556387_Idx][off+i] = y_33556388.charCodeAt(i);
      }
    

  
}

function isFatPointer_33557200(ti_33557201) {
  var result_33557202 = false;

  BeforeRet: {
    result_33557202 = !((ConstSet1[ti_33557201.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557202;

}

function nimCopyAux(dest_33557213, src_33557214, n_33557215) {
    switch (n_33557215.kind) {
    case 0:
      break;
    case 1:
            dest_33557213[n_33557215.offset] = nimCopy(dest_33557213[n_33557215.offset], src_33557214[n_33557215.offset], n_33557215.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557215.sons.length; i++) {
      nimCopyAux(dest_33557213, src_33557214, n_33557215.sons[i]);
    }
    
      break;
    case 3:
            dest_33557213[n_33557215.offset] = nimCopy(dest_33557213[n_33557215.offset], src_33557214[n_33557215.offset], n_33557215.typ);
      for (var i = 0; i < n_33557215.sons.length; ++i) {
        nimCopyAux(dest_33557213, src_33557214, n_33557215.sons[i][1]);
      }
    
      break;
    }

  
}

function auxWriteStackTrace_33556512(f_33556513) {
  var result_33556514 = [[]];

    var it_33556522 = f_33556513;
    var i_33556523 = 0;
    var total_33556524 = 0;
    var tempFrames_33556525 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555824);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556522 == null)) && (i_33556523 <= 63))) break Label2;
          tempFrames_33556525[i_33556523].Field0 = it_33556522.procname;
          tempFrames_33556525[i_33556523].Field1 = it_33556522.line;
          tempFrames_33556525[i_33556523].Field2 = it_33556522.filename;
          i_33556523 += 1;
          total_33556524 += 1;
          it_33556522 = it_33556522.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556522 == null))) break Label4;
          total_33556524 += 1;
          it_33556522 = it_33556522.prev;
        }
    };
    result_33556514[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556524 == i_33556523))) {
    result_33556514[0].push.apply(result_33556514[0], [40]);;
    result_33556514[0].push.apply(result_33556514[0], HEX24_369098760((total_33556524 - i_33556523)));;
    result_33556514[0].push.apply(result_33556514[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556558 = 0;
      var colontmp__973078632 = 0;
      colontmp__973078632 = (i_33556523 - 1);
      var res_973078634 = colontmp__973078632;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_973078634)) break Label7;
            j_33556558 = res_973078634;
            result_33556514[0].push.apply(result_33556514[0], cstrToNimstr(tempFrames_33556525[j_33556558].Field2));;
            if ((0 < tempFrames_33556525[j_33556558].Field1)) {
            result_33556514[0].push.apply(result_33556514[0], [40]);;
            addInt_301990111(result_33556514, 0, tempFrames_33556525[j_33556558].Field1);
            if (false) {
            result_33556514[0].push.apply(result_33556514[0], [44,32]);;
            addInt_301990111(result_33556514, 0, 0);
            }
            
            result_33556514[0].push.apply(result_33556514[0], [41]);;
            }
            
            result_33556514[0].push.apply(result_33556514[0], [32,97,116,32]);;
            add_33556386(result_33556514, 0, tempFrames_33556525[j_33556558].Field0);
            result_33556514[0].push.apply(result_33556514[0], [10]);;
            res_973078634 -= 1;
          }
      };
    };

  return result_33556514[0];

}

function rawWriteStackTrace_33556599() {
  var result_33556600 = [];

    if (!((framePtr == null))) {
    result_33556600 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556512(framePtr) || []), NTI33554449);
    }
    else {
      result_33556600 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556600;

}

function newSeq_33556872(len_33556874) {
  var result_33556875 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 597;
    result_33556875 = new Array(len_33556874); for (var i = 0 ; i < len_33556874 ; ++i) { result_33556875[i] = null; }  framePtr = F.prev;

  return result_33556875;

}

function unhandledException(e_33556638) {
    var buf_33556639 = [[]];
    if (!(((e_33556638.message).length == 0))) {
    buf_33556639[0].push.apply(buf_33556639[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556639[0].push.apply(buf_33556639[0], e_33556638.message);;
    }
    else {
    buf_33556639[0].push.apply(buf_33556639[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556639[0].push.apply(buf_33556639[0], [32,91]);;
    add_33556386(buf_33556639, 0, e_33556638.name);
    buf_33556639[0].push.apply(buf_33556639[0], [93,10]);;
    buf_33556639[0].push.apply(buf_33556639[0], rawWriteStackTrace_33556599());;
    var cbuf_33556640 = toJSStr(buf_33556639[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556640);
  }
  else {
    throw cbuf_33556640;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556995) {
        if (a_33556995 > 2147483647 || a_33556995 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556777, a_33556778, b_33556779) {
    var Temporary1;

    if ((b_33556779 < a_33556778)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_369098760(i_33556777) || [],[32,110,111,116,32,105,110,32] || [],HEX24_369098760(a_33556778) || [],[32,46,46,32] || [],HEX24_369098760(b_33556779) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_301990072(result_301990074, result_301990074_Idx, x_301990075, start_301990076, n_301990077) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    var old_301990078 = (result_301990074[result_301990074_Idx]).length;
    F.line = 44;
    if (result_301990074[result_301990074_Idx].length < (Temporary1 = chckRange(addInt(old_301990078, n_301990077), 0, 2147483647), Temporary1)) { for (var i = result_301990074[result_301990074_Idx].length; i < Temporary1; ++i) result_301990074[result_301990074_Idx].push(0); }
         else {result_301990074[result_301990074_Idx].length = Temporary1; };
    Label2: {
      F.line = 46;
      var iHEX60gensym4_301990092 = 0;
      F.line = 119;
      var i_973078627 = 0;
      Label3: {
        F.line = 120;
          Label4: while (true) {
          if (!(i_973078627 < n_301990077)) break Label4;
            F.line = 49;
            iHEX60gensym4_301990092 = i_973078627;
            F.line = 49;
            result_301990074[result_301990074_Idx][chckIndx(addInt(old_301990078, iHEX60gensym4_301990092), 0, (result_301990074[result_301990074_Idx]).length - 1)] = x_301990075.charCodeAt(chckIndx(addInt(start_301990076, iHEX60gensym4_301990092), 0, (x_301990075).length - 1));
            F.line = 122;
            i_973078627 = addInt(i_973078627, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_301990068(result_301990070, result_301990070_Idx, x_301990071) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    addChars_301990072(result_301990070, result_301990070_Idx, x_301990071, 0, ((x_301990071) == null ? 0 : (x_301990071).length));
  framePtr = F.prev;

  
}

function addInt_301990093(result_301990094, result_301990094_Idx, x_301990095) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 111;
    addChars_301990068(result_301990094, result_301990094_Idx, ((x_301990095) + ""));
  framePtr = F.prev;

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 115;
    addInt_301990093(result_301990112, result_301990112_Idx, x_301990113);
  framePtr = F.prev;

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    addInt_301990111(result_369098762, 0, x_369098761);
  framePtr = F.prev;

  return result_369098762[0];

}
async function fn_973078535(n_973078536) {
  var result_973078538 = null;

  var F = {procname: "asyncjs_examples_2.fn", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
    if ((7 <= n_973078536)) {
    F.line = 249;
    raiseException({message: ([102,111,111,98,97,114,58,32] || []).concat(HEX24_369098760(n_973078536) || []), parent: null, m_type: NTI134217746, name: null, trace: [], up: null}, "ValueError");
    }
    else {
      F.line = 249;
      result_973078538 = mulInt(n_973078536, 2);
    }
    
  framePtr = F.prev;

  return result_973078538;

}

function sysFatal_268435497(message_268435500) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 51;
    raiseException({message: nimCopy(null, message_268435500, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_268435495(msg_268435496) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    sysFatal_268435497(msg_268435496);
  framePtr = F.prev;

  
}

function failedAssertImpl_268435531(msg_268435532) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 46;
    raiseAssert_268435495(msg_268435532);
  framePtr = F.prev;

  
}

function nsuFindChar(s_989857437, sub_989857438, start_989857439, last_989857440) {
    var Temporary1;

  var result_989857441 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1913;
    result_989857441 = -1;
    F.line = 1914;
    if ((last_989857440 < 0)) {
    Temporary1 = (s_989857437).length - 1;
    }
    else {
    Temporary1 = last_989857440;
    }
    
    var last_989857442 = Temporary1;
    Label2: {
      F.line = 1917;
      var iHEX60gensym176_989857456 = 0;
      F.line = 75;
      var colontmp__973078643 = 0;
      F.line = 1917;
      colontmp__973078643 = start_989857439;
      F.line = 90;
      var res_973078644 = colontmp__973078643;
      Label3: {
        F.line = 91;
          Label4: while (true) {
          if (!(res_973078644 <= last_989857442)) break Label4;
            F.line = 1931;
            iHEX60gensym176_989857456 = res_973078644;
            if ((s_989857437[chckIndx(iHEX60gensym176_989857456, 0, (s_989857437).length - 1)] == sub_989857438)) {
            F.line = 1919;
            result_989857441 = iHEX60gensym176_989857456;
            break BeforeRet;
            }
            
            F.line = 93;
            res_973078644 = addInt(res_973078644, 1);
          }
      };
    };
  };
  framePtr = F.prev;

  return result_989857441;

}

function nsuFindStrA(a_989857415, s_989857416, sub_989857417, start_989857418, last_989857419) {
    var Temporary1;

  var result_989857420 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1873;
    if ((last_989857419 < 0)) {
    Temporary1 = (s_989857416).length - 1;
    }
    else {
    Temporary1 = last_989857419;
    }
    
    var last_989857421 = Temporary1;
    F.line = 1874;
    var subLast_989857422 = subInt((sub_989857417).length, 1);
    if ((subLast_989857422 == -1)) {
    F.line = 1879;
    result_989857420 = start_989857418;
    break BeforeRet;
    }
    
    F.line = 1883;
    result_989857420 = -1;
    F.line = 1884;
    var skip_989857423 = start_989857418;
    Label2: {
      F.line = 1886;
        Label3: while (true) {
        if (!(subLast_989857422 <= subInt(last_989857421, skip_989857423))) break Label3;
          F.line = 1887;
          var i_989857424 = subLast_989857422;
          Label4: {
            F.line = 1888;
              Label5: while (true) {
              if (!(s_989857416[chckIndx(addInt(skip_989857423, i_989857424), 0, (s_989857416).length - 1)] == sub_989857417[chckIndx(i_989857424, 0, (sub_989857417).length - 1)])) break Label5;
                if ((i_989857424 == 0)) {
                F.line = 1890;
                result_989857420 = skip_989857423;
                break BeforeRet;
                }
                
                F.line = 1891;
                i_989857424 = subInt(i_989857424, 1);
              }
          };
          F.line = 1892;
          skip_989857423 = addInt(skip_989857423, a_989857415[chckIndx(s_989857416[chckIndx(addInt(skip_989857423, subLast_989857422), 0, (s_989857416).length - 1)], 0, (a_989857415).length - 1)]);
        }
    };
  };
  framePtr = F.prev;

  return result_989857420;

}

function fill_989857365(a_989857367, value_989857368) {
  var F = {procname: "fill.fill", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
  framePtr = F;
    F.line = 72;
    var xHEX60gensym172_989857374 = 0;
    Label1: {
      F.line = 98;
        Label2: while (true) {
        if (!(xHEX60gensym172_989857374 <= (a_989857367).length - 1)) break Label2;
          F.line = 98;
          a_989857367[chckIndx(xHEX60gensym172_989857374, 0, (a_989857367).length - 1)] = value_989857368;
          F.line = 75;
          xHEX60gensym172_989857374 = addInt(xHEX60gensym172_989857374, 1);
        }
    };
  framePtr = F.prev;

  
}

function nsuInitSkipTable(a_989857362, sub_989857363) {
  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1846;
    var m_989857364 = (sub_989857363).length;
    F.line = 1847;
    fill_989857365(a_989857362, m_989857364);
    Label1: {
      F.line = 1849;
      var i_989857384 = 0;
      F.line = 117;
      var colontmp__973078649 = 0;
      F.line = 1849;
      colontmp__973078649 = subInt(m_989857364, 1);
      F.line = 119;
      var i_973078650 = 0;
      Label2: {
        F.line = 120;
          Label3: while (true) {
          if (!(i_973078650 < colontmp__973078649)) break Label3;
            F.line = 1849;
            i_989857384 = i_973078650;
            F.line = 1849;
            a_989857362[chckIndx(sub_989857363[chckIndx(i_989857384, 0, (sub_989857363).length - 1)], 0, (a_989857362).length - 1)] = subInt(subInt(m_989857364, 1), i_989857384);
            F.line = 122;
            i_973078650 = addInt(i_973078650, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function nsuInitNewSkipTable(sub_989857412) {
  var result_989857413 = [new Int32Array(256)];

  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1859;
    nsuInitSkipTable(result_989857413[0], sub_989857412);
  framePtr = F.prev;

  return result_989857413[0];

}

function nsuFindStr(s_989857474, sub_989857475, start_989857476, last_989857477) {
  var result_989857478 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((subInt((s_989857474).length, start_989857476) < (sub_989857475).length)) {
    F.line = 1971;
    result_989857478 = -1;
    break BeforeRet;
    }
    
    if (((sub_989857475).length == 1)) {
    F.line = 1972;
    result_989857478 = nsuFindChar(s_989857474, sub_989857475[chckIndx(0, 0, (sub_989857475).length - 1)], start_989857476, last_989857477);
    break BeforeRet;
    }
    
    F.line = 1975;
    result_989857478 = nsuFindStrA(nsuInitNewSkipTable(sub_989857475), s_989857474, sub_989857475, start_989857476, last_989857477);
  };
  framePtr = F.prev;

  return result_989857478;

}

function contains_989857616(s_989857617, sub_989857618) {
  var result_989857619 = false;

  var F = {procname: "strutils.contains", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 2129;
    result_989857619 = (0 <= nsuFindStr(s_989857617, sub_989857618, 0, -1));
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_989857619;

}
async function main_973078553() {
    
function HEX3Aanonymous_973078563(r_973078564) {
      var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
      framePtr = F;
        F.line = 249;
        reason_973078561 = r_973078564;
      framePtr = F.prev;

      
    }
    
function HEX3Aanonymous_973078598(r_973078599) {
      var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
      framePtr = F;
        F.line = 249;
        reason_973078561 = r_973078599;
      framePtr = F.prev;

      
    }

  var result_973078555 = null;

  var F = {procname: "asyncjs_examples_2.main", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 249;
    var reason_973078561 = null;
    F.line = 249;
    (await catch_973078579(fn_973078535(6), HEX3Aanonymous_973078563));
    if (!((reason_973078561 == null))) {
    F.line = 249;
    failedAssertImpl_268435531(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(18, 5) `reason == nil` "));
    }
    
    F.line = 249;
    (await catch_973078579(fn_973078535(7), HEX3Aanonymous_973078598));
    if (!(!((reason_973078561 == null)))) {
    F.line = 249;
    failedAssertImpl_268435531(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(20, 5) `reason != nil` "));
    }
    
    if (!(contains_989857616(cstrToNimstr(reason_973078561.message), [102,111,111,98,97,114,58,32,55]))) {
    F.line = 249;
    failedAssertImpl_268435531(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(21, 5) `\"foobar: 7\" in $reason.message` "));
    }
    
    F.line = 249;
    result_973078555 = undefined;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_973078555;

}
var F = {procname: "module asyncjs_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
framePtr = F;
F.line = 249;
var _ = main_973078553();
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
